export const SERUM_ORDERBOOK_UPDATE = 'SERUM_ORDERBOOK_UPDATE'
export const SERUM_TRADES_UPDATE = 'SERUM_TRADES_UPDATE'

export const SERUM_UI_MARKET_CHANGED = 'SERUM_UI_MARKET_CHANGED'
export const SERUM_UI_WALLET_CONNECTED = 'SERUM_UI_WALLET_CONNECTED'
export const SERUM_UI_INITIALIZATION_IN_PROGRESS =
  'SERUM_UI_INITIALIZATION_IN_PROGRESS'
export const SERUM_UI_INITIALIZATION_COMPLETE =
  'SERUM_UI_INITIALIZATION_COMPLETE'
export const SERUM_UI_SETTLEMENT_IN_PROGRESS = 'SERUM_UI_SETTLEMENT_IN_PROGRESS'
export const SERUM_UI_SETTLEMENT_COMPLETE = 'SERUM_UI_SETTLEMENT_COMPLETE'
export const SERUM_UI_WALLET_DISCONNECTED = 'SERUM_UI_WALLET_DISCONNECTED'
export const SERUM_UI_BASE_CURRENCY_CHANGED = 'SERUM_UI_BASE_CURRENCY_CHANGED'
export const SERUM_UI_QUOTE_CURRENCY_CHANGED = 'SERUM_UI_QUOTE_CURRENCY_CHANGED'
// export const SERUM_UI_BASE_CURRENCY_BALANCE_CHANGED = 'SERUM_UI_BASE_CURRENCY_BALANCE_CHANGED';
export const SERUM_UI_BASE_WALLET_BALANCE_CHANGED =
  'SERUM_UI_BASE_WALLET_BALANCE_CHANGED'
export const SERUM_UI_BASE_UNSETTLED_BALANCE_CHANGED =
  'SERUM_UI_BASE_UNSETTLED_BALANCE_CHANGED'
// export const SERUM_UI_QUOTE_CURRENCY_BALANCE_CHANGED = 'SERUM_UI_QUOTE_CURRENCY_BALANCE_CHANGED';
export const SERUM_UI_QUOTE_WALLET_BALANCE_CHANGED =
  'SERUM_UI_QUOTE_WALLET_BALANCE_CHANGED'
export const SERUM_UI_QUOTE_UNSETTLED_BALANCE_CHANGED =
  'SERUM_UI_QUOTE_UNSETTLED_BALANCE_CHANGED'
export const SERUM_UI_ORDER_MESSAGE_CHANGED = 'SERUM_UI_ORDER_MESSAGE_CHANGED'
export const SERUM_UI_ORDER_TYPE_CHANGED = 'SERUM_UI_ORDER_TYPE_CHANGED'
export const SERUM_UI_OPEN_ORDERS_UPDATED = 'SERUM_UI_OPEN_ORDERS_UPDATED'
export const SERUM_UI_ORDER_IS_PLACED = 'SERUM_UI_ORDER_IS_PLACED'
export const SERUM_UI_SMART_ORDER_EVENT = 'SERUM_UI_SMART_ORDER_EVENT'
