const ASSETS_BASEURL =
  'https://globalliquidity.blob.core.windows.net/bionictraderassets'
const Assets = {
  Models: {
    EnvTokyoNightBlur: `${ASSETS_BASEURL}/models/TokyoNightBlur.env`,
    EnvMorningSkyRipple: `${ASSETS_BASEURL}/models/MorningSkyRipple.env`,
    EnvMorningSkyRipple1: `${ASSETS_BASEURL}/models/MorningSkyRipple1.env`,
    EnvMorningSkyRippleSimple: `${ASSETS_BASEURL}/models/MorningSkyRippleSimple.env`,
    EnvBrighterSky2048: `${ASSETS_BASEURL}/models/BrighterSky2048.env`,
    EnvBrighterSky: `${ASSETS_BASEURL}/models/BrighterSky.env`,
    EnvSimpleSky: `${ASSETS_BASEURL}/models/SimpleSky2048.env`,
    EnvStratoshphere: `${ASSETS_BASEURL}/models/Stratosphere.env`,
    DdsSimpleSky512: `${ASSETS_BASEURL}/models/SimpleSky512.dds`,
    DdsTokyo: `${ASSETS_BASEURL}/models/TokyoNightBlurSpecularHDR.dds`,
    DdsPlaya: `${ASSETS_BASEURL}/models/playa_sunriseSpecularHDR.dds`,
    DdsLA: `${ASSETS_BASEURL}/models/LA_Sky.dds`,
    DdsPlayaSunriseHDR: `${ASSETS_BASEURL}/models/playa_sunriseSpecularHDR.dds`,
    GlbStartButtonBackground: `${ASSETS_BASEURL}/models/StartButtonBackground.glb`,
    GlbStartButtonText: `${ASSETS_BASEURL}/models/StartButtonTextBlender.glb`,
    GlbRightArrow: `${ASSETS_BASEURL}/models/RightArrowSmooth.glb`,
    GlbArrowBackground: `${ASSETS_BASEURL}/models/ArrowBackground.glb`,
    GlbExitTrade: `${ASSETS_BASEURL}/models/ExitTradeNew.glb`,
    GlbTradeText: `${ASSETS_BASEURL}/models/startText.glb`,
    GlbStartText: `${ASSETS_BASEURL}/models/TradeText.glb`,
    GlbPositionPointer: `${ASSETS_BASEURL}/models/PositionPointer.glb`,
    GlbplusModel: `${ASSETS_BASEURL}/models/Plus.glb`,
    GlbMinusModel: `${ASSETS_BASEURL}/models/Minus.glb`,
    GlbGemModel: `${ASSETS_BASEURL}/models/GemNew.glb`,
    BabylonFontConthrax: `${ASSETS_BASEURL}/models/Font_Conthrax_New.babylon.gz`,
    BabylonSimpleCubeModel: `${ASSETS_BASEURL}/models/simplecube.babylon.gz`,
    BabylonMarkerModel: `${ASSETS_BASEURL}/models/ordermarker2.babylon.gz`,
    BabylonHudFrame: `${ASSETS_BASEURL}/models/HUDFrame600.babylon.gz`,
    BabylonTubeSegment: `${ASSETS_BASEURL}/models/TubeSegment.babylon.gz`,
    BabylonCircularArrow: `${ASSETS_BASEURL}/models/CircularArrow.babylon.gz`,
    BabylonIcebergModel: `${ASSETS_BASEURL}/models/Iceberg.babylon.gz`,
    BabylonIcebergBase: `${ASSETS_BASEURL}/models/Iceberg_BaseColor.babylon.gz`,
    BabylonCandleModel: `${ASSETS_BASEURL}/models/candle.babylon.gz`,
    BabylonStartButtonBackground: `${ASSETS_BASEURL}/models/StartButtonBackground.babylon.gz`,
    BabylonTradeText: `${ASSETS_BASEURL}/models/TradeText.babylon.gz`,
    BabylonStartText: `${ASSETS_BASEURL}/models/startText.babylon.gz`,
    BabylonUserIcon: `${ASSETS_BASEURL}/models/user-icon.babylon`,
    BabylonDownArrow: `${ASSETS_BASEURL}/models/DownArrow.babylon.gz`,
  },
  Sounds: {
    WavBidUpSound: `${ASSETS_BASEURL}/sounds-gz/BidUpQuiet2.wav.gz`,
    WavBidDownSound: `${ASSETS_BASEURL}/sounds-gz/BidDownQuiet.wav.gz`,
    WavAskUpSound: `${ASSETS_BASEURL}/sounds-gz/AskUpQuiet.wav.gz`,
    WavAskDownSound: `${ASSETS_BASEURL}/sounds-gz/AskDownQuiet.wav.gz`,
    WavBidFillSound: `${ASSETS_BASEURL}/sounds-gz/BidFill.wav.gz`,
    WavAskFillSound: `${ASSETS_BASEURL}/sounds-gz/AskFill.wav.gz`,
    WavTradeWinSound: `${ASSETS_BASEURL}/sounds-gz/TradeWin.wav.gz`,
    WavTradeLossSound: `${ASSETS_BASEURL}/sounds-gz/TradeLoss.wav.gz`,
    WavEngageSound: `${ASSETS_BASEURL}/sounds-gz/Engage.wav.gz`,
    WavDisengageSound: `${ASSETS_BASEURL}/sounds-gz/Disengage.wav.gz`,
    WavBleepSoundC2: `${ASSETS_BASEURL}/sounds-gz/BleepC2.wav.gz`,
    WavBleepSoundEf2: `${ASSETS_BASEURL}/sounds-gz/BleepEf2.wav.gz`,
    WavBleepSoundE2: `${ASSETS_BASEURL}/sounds-gz/BleepE2.wav.gz`,
    WavBleepSoundF2: `${ASSETS_BASEURL}/sounds-gz/BleepF2.wav.gz`,
    WavBleepSoundG2: `${ASSETS_BASEURL}/sounds-gz/BleepG2.wav.gz`,
    WavBleepSoundBf2: `${ASSETS_BASEURL}/sounds-gz/BleepBf2.wav.gz`,
    WavBleepSoundB2: `${ASSETS_BASEURL}/sounds-gz/BleepB2.wav.gz`,
    WavbleepSoundC3: `${ASSETS_BASEURL}/sounds-gz/BleepC3.wav.gz`,
    WavBleepSoundEf3: `${ASSETS_BASEURL}/sounds-gz/BleepEf3.wav.gz`,
    WavBleepSoundE3: `${ASSETS_BASEURL}/sounds-gz/BleepE3.wav.gz`,
    WavBleepSoundF3: `${ASSETS_BASEURL}/sounds-gz/BleepF3.wav.gz`,
    WavBleepSoundG3: `${ASSETS_BASEURL}/sounds-gz/BleepG3.wav.gz`,
    WavBleepSoundB3: `${ASSETS_BASEURL}/sounds-gz/BleepB3.wav.gz`,
    WavBleepSoundC4: `${ASSETS_BASEURL}/sounds-gz/BleepC34.wav.gz`,
    WavBleepSoundE4: `${ASSETS_BASEURL}/sounds-gz/BleepE4.wav.gz`,
    WavBleepSoundF4: `${ASSETS_BASEURL}/sounds-gz/BleepF4.wav.gz`,
    WavBleepSoundG4: `${ASSETS_BASEURL}/sounds-gz/BleepG4.wav.gz`,
    WavBleepSoundB4: `${ASSETS_BASEURL}/sounds-gz/BleepB4.wav.gz`,
    WavBleepSoundC5: `${ASSETS_BASEURL}/sounds-gz/BleepC5.wav.gz`,
    WavBleepSoundE5: `${ASSETS_BASEURL}/sounds-gz/BleepE5.wav.gz`,
    WavBleepSoundF5: `${ASSETS_BASEURL}/sounds-gz/BleepF5.wav.gz`,
    WavTradeSoundC3: `${ASSETS_BASEURL}/sounds-gz/TradeC3.wav.gz`,
    WavTradeSoundE3: `${ASSETS_BASEURL}/sounds-gz/TradeE3.wav.gz`,
    WavTradeSoundF3: `${ASSETS_BASEURL}/sounds-gz/TradeF3.wav.gz`,
    WavTradeSoundG3: `${ASSETS_BASEURL}/sounds-gz/TradeG3.wav.gz`,
    WavTradeSoundB3: `${ASSETS_BASEURL}/sounds-gz/TradeB3.wav.gz`,
    WavTradeSoundC4: `${ASSETS_BASEURL}/sounds-gz/TradeC4.wav.gz`,
    WavTradeSoundE4: `${ASSETS_BASEURL}/sounds-gz/TradeE4.wav.gz`,
    WavTradeSoundF4: `${ASSETS_BASEURL}/sounds-gz/TradeF4.wav.gz`,
    WavTradeSoundG4: `${ASSETS_BASEURL}/sounds-gz/TradeG4.wav.gz`,
    WavTradeSoundB4: `${ASSETS_BASEURL}/sounds-gz/TradeB4.wav.gz`,
    WavTradeSoundC5: `${ASSETS_BASEURL}/sounds-gz/TradeC5.wav.gz`,
    WavTradeSoundE5: `${ASSETS_BASEURL}/sounds-gz/TradeE5.wav.gz`,
    WavTradeSoundF5: `${ASSETS_BASEURL}/sounds-gz/TradeF5.wav.gz`,
    WavPriceZoomInSound: `${ASSETS_BASEURL}/sounds-gz/PriceZoomIn.wav.gz`,
    WavPriceZoomOutSound: `${ASSETS_BASEURL}/sounds-gz/PriceZoomOut.wav.gz`,
    WavPriceZoomNoneSound: `${ASSETS_BASEURL}/sounds-gz/PriceZoomNone.wav.gz`,
    WavPlayerJoinSound: `${ASSETS_BASEURL}/sounds-gz/PlayerJoin.wav.gz`,
    WavMarketMovesUpOne: `${ASSETS_BASEURL}/sounds-gz/MarketUpOneV2.wav.gz`,
    WavMarketMovesDownOne: `${ASSETS_BASEURL}/sounds-gz/MarketDownOneV2.wav.gz`,
    WavMarketMovesUpTen: `${ASSETS_BASEURL}/sounds-gz/MarketUpTenV2.wav.gz`,
    WavMarketMovesDownTen: `${ASSETS_BASEURL}/sounds-gz/MarketDownTenV2.wav.gz`,
    WavPopupOpen: `${ASSETS_BASEURL}/sounds-gz/PopupOpenV1.wav.gz`,
    WavPopupClose: `${ASSETS_BASEURL}/sounds-gz/PopupCloseV1.wav.gz`,
    WavButtonClick: `${ASSETS_BASEURL}/sounds-gz/ButtonClickV1.wav.gz`,
    WavSelectUp: `${ASSETS_BASEURL}/sounds-gz/SelectUpV1.wav.gz`,
    WavSelectDown: `${ASSETS_BASEURL}/sounds-gz/SelectDownV1.wav.gz`,
    WavProgressLoop: `${ASSETS_BASEURL}/sounds-gz/ProgressLoopV1.wav.gz`,
    WavProgressComplete: `${ASSETS_BASEURL}/sounds-gz/ProgressCompleteV1.wav.gz`,
    WavPurchaseComplete: `${ASSETS_BASEURL}/sounds-gz/PurchaseCompleteV1.wav.gz`,
    Mp3CountdownFive: `${ASSETS_BASEURL}/sounds/Countdown_FiveV1.mp3`,
    Mp3CountdownFour: `${ASSETS_BASEURL}/sounds/Countdown_FourV1.mp3`,
    Mp3CountdownThree: `${ASSETS_BASEURL}/sounds/Countdown_ThreeV1.mp3`,
    Mp3CountdownTwo: `${ASSETS_BASEURL}/sounds/Countdown_TwoV1.mp3`,
    Mp3CountdownOne: `${ASSETS_BASEURL}/sounds/Countdown_OneV1.mp3`,
    Mp3CountdownTrade: `${ASSETS_BASEURL}/sounds/Countdown_TradeV1.mp3`,
    JoinRound: `${ASSETS_BASEURL}/sounds/LeaveRoundV1.mp3`, //I accidentally rendered them in reverse
    LeaveRound: `${ASSETS_BASEURL}/sounds/JoinRoundV1.mp3`,
    TradeWinSmall: `${ASSETS_BASEURL}/sounds/TradeWinSmall.mp3`,
    TradeLossSmall: `${ASSETS_BASEURL}/sounds/TradeLossSmall.mp3`,
    PositionUpTick: `${ASSETS_BASEURL}/sounds/PositionUpTickV1.mp3`,
    PositionDownTick: `${ASSETS_BASEURL}/sounds/PositionDownTickV1.mp3`,
    PlayerTakesGem: `${ASSETS_BASEURL}/sounds/PlayerTakesGemV1.mp3`,
    PlayerForfeitsGem: `${ASSETS_BASEURL}/sounds/PlayerForfeitsGemV1.mp3`,
    OrderPlaced: `${ASSETS_BASEURL}/sounds-gz/OrderPlacedV1.wav.gz`,
    OrderPlacedProgress: `${ASSETS_BASEURL}/sounds-gz/OrderPlacedProgressV1.wav.gz`,
    OrderConfirmed: `${ASSETS_BASEURL}/sounds-gz/OrderConfirmedV1.wav.gz`,
    OrderCancelRequested: `${ASSETS_BASEURL}/sounds-gz/OrderCancelRequestedV1.wav.gz`,
    Synchronizing: `${ASSETS_BASEURL}/sounds-gz/SynchronizingV2.wav.gz`,
    SettlingFunds: `${ASSETS_BASEURL}/sounds-gz/SettlingFundsV2.wav.gz`,
    Mp3LobbyMusic: `${ASSETS_BASEURL}/sounds/LobbyMusicV2.mp3`,
  },
  Images: {
    // pngLogo: `${ASSETS_BASEURL}/images/Logo.png`,
    pngReferenceLandscape: `${ASSETS_BASEURL}/images/reference_landscape.png.gz`,
    pngReferencePortrait: `${ASSETS_BASEURL}/images/reference_portrait.jpg.gz`,
    pngTwentyColorPaletteBlack: `${ASSETS_BASEURL}/images/20ColorPaletteBlack.png.gz`,
    pngWaterbump: `${ASSETS_BASEURL}/images/waterbump.png.gz`,
    pngSecuredByOpenNode: `${ASSETS_BASEURL}/images/SecuredByOpenNode.png`,
    pngSecuredByOpenNodeOpacity: `${ASSETS_BASEURL}/images/SecuredByOpenNode_opacity.png`,

    // themeButton: `${ASSETS_BASEURL}/images/button_theme.png`,
    // medal1: `${ASSETS_BASEURL}/images/first_medal.png`,
    // medal2: `${ASSETS_BASEURL}/images/second_medal.png`,
    // medal3: `${ASSETS_BASEURL}/images/third_medal.png`,
    pngBidBuyCircle: `${ASSETS_BASEURL}/images/BidBuyCircle.png.gz`,
    pngAskSellCircle: `${ASSETS_BASEURL}/images/AskSellCircle.png.gz`,
    bwLUT: `${ASSETS_BASEURL}/images/bwLUT.png.gz`,
    // richpinkLut: `${ASSETS_BASEURL}/images/richpinklut.png`,
    // arcticBeautyLut: `${ASSETS_BASEURL}/images/arcticBeautyLut.png`,
    // icebergBase: `${ASSETS_BASEURL}/images/Iceberg_BaseColor.png`,
    // icebergNormal: `${ASSETS_BASEURL}/images/Iceberg_Normal.png`,
    // icebergRoughness: `${ASSETS_BASEURL}/images/Iceberg_Roughness.png`,
    // backgroundImage: `${ASSETS_BASEURL}/images/background_image.jpg`,
    // bionicTraderLogo: `${ASSETS_BASEURL}/images/bionic_trader_logo.jpg`,
    thumbMorningTheme: `${ASSETS_BASEURL}/images/morning_theme111.png`,
    thumbDayTheme: `${ASSETS_BASEURL}/images/day_theme111.png`,
    thumbNightTheme: `${ASSETS_BASEURL}/images/night_theme111.png`,
    // iceTexture: `${ASSETS_BASEURL}/images/ice-plane1.jpg`,
  },
}

export default Assets
